11649 as new link
idea-statica/ideastatica-public pull request #244
Opened 2023-02-17 09:36 UTC by vadura-pavel

Bim Link add support for Cad models

2023-02-17 14:35 UTC, dbacovsky requested changes

2023-02-17 14:35 UTC, dbacovsky commented on src/IdeaStatiCa.BimApi/IIdeaPlate.cs
> +		IdeaRS.OpenModel.Geometry3D.CoordSystem LocalCoordinateSystem { get; set; }
Nedávat settery do bimapi interfaců.

2023-02-17 14:35 UTC, dbacovsky commented on src/IdeaStatiCa.BimImporter/BimImporter.cs
> +									 (c.ReferencedObject as IIdeaConnectionPoint).Node, 1E-08)
Hodnoty pro přesnost přidat/použít z BimImporterConfiguration

2023-02-17 14:35 UTC, dbacovsky commented on src/IdeaStatiCa.BimImporter/Persistence/PersistenceTokenConverter.cs
> +			return obj.GetValue(DataName).ToObject(type, GetJsonSerializer());
Nevím, jestli nám ta změna serializace nerozbije staré projekty.

2023-02-17 14:35 UTC, dbacovsky commented on src/IdeaStatica.BimApiLink/Utils/WindowVisibilityHelper.cs
> +	public static class WindowVisibilityHelper
Má tohle tady vůbec být?

2023-02-17 14:35 UTC, dbacovsky commented on src/IdeaStatica.BimApiLink/Identifiers/ConnectedMemberIdentidier.cs
> +	public class ConnectedMemberIdentidier<T> : StringIdentifier<T>
překlep

2023-02-17 14:38 UTC, hronlukas commented on src/IdeaStatiCa.BimApi/IIdeaBend.cs
> +	public interface IIdeaBend : IIdeaObject
Možná bychom mohli popsat interface.

2023-02-20 08:53 UTC, vadura-pavel commented on src/IdeaStatiCa.BimApi/IIdeaPlate.cs
> +		IdeaRS.OpenModel.Geometry3D.CoordSystem LocalCoordinateSystem { get; set; }
fix

2023-02-20 08:54 UTC, vadura-pavel commented on src/IdeaStatiCa.BimImporter/BimImporter.cs
> +									 (c.ReferencedObject as IIdeaConnectionPoint).Node, 1E-08)
fix

2023-02-20 08:54 UTC, vadura-pavel commented on src/IdeaStatiCa.BimImporter/Persistence/PersistenceTokenConverter.cs
> +			return obj.GetValue(DataName).ToObject(type, GetJsonSerializer());
davame to az do 23 cili mozna nekompatibilita zas tolik nevadi

2023-02-20 08:57 UTC, vadura-pavel commented on src/IdeaStatica.BimApiLink/Identifiers/ConnectedMemberIdentidier.cs
> +	public class ConnectedMemberIdentidier<T> : StringIdentifier<T>
fix

2023-02-20 09:31 UTC, vadura-pavel commented on src/IdeaStatica.BimApiLink/Utils/WindowVisibilityHelper.cs
> +	public static class WindowVisibilityHelper
Idealne to dat nekam na spolecne misto mas nejaky tip?

2023-02-21 06:35 UTC, vadura-pavel commented on src/IdeaStatiCa.BimImporter/Persistence/PersistenceTokenConverter.cs
> +			return obj.GetValue(DataName).ToObject(type, GetJsonSerializer());
testovano a bez teto opravy AS link nefunguje

2023-02-22 15:49 UTC, dbacovsky approved these changes

2023-02-22 15:52 UTC, merged